/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author gsus
 * @date 03-04-2017 14.56
 */
import static ratpack.groovy.Groovy.ratpack

ratpack {
	// cors headers
	include 'modules/cors.groovy'

	// external file conf
	include 'modules/server-config.groovy'

	// charts
	include 'modules/charts.groovy'

	// logging (have to be the last one)
	include 'modules/request-log.groovy'
}
